---
- name: Provision instance in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    security_group_id: sg-0252de2d3594fc0e0
    ami_id: ami-09d6d9540936a68de
    instance_size: m4.xlarge
    instance_tags: {"Name":"mkb-platform-ec2-instance"}
    region: 
    vpc_id: vpc-03ff2668
    ssh_key_name: mkb-platform


  collections: 
    - amazon.aws

  tasks:
  - name: Provision instance
    amazon.aws.ec2:
      key_name: "{{ ssh_key_name }}"
      group_id: "{{ security_group_id }}"
      instance_type: "{{ instance_size }}"
      instance_tags: "{{ instance_tags }}"
      image: "{{ ami_id }}"
      wait: yes
      vpc_subnet_id: "{{ vpc_id }}"
      assign_public_ip: no
