---
- name: Provision instance in AWS
  hosts: localhost
  gather_facts: false
  vars:
    security_group: mkb-platform-sg
    ami_id: ami-09d6d9540936a68de
    instance_size: m4.xlarge
    instance_tags: {"Name":"mkb-platform-ec2-instance"}
    vpc_id: vpc-094c7a2bae802020b
    ssh_key_name: mkb-platform
    region: us-east-2
    subnet_id: subnet-05cdfa73ae7fdd656


  collections: 
    - amazon.aws

  tasks:
  - name: Provision instance
    amazon.aws.ec2:
      region: "{{ region }}"
      key_name: "{{ ssh_key_name }}"
      group: "{{ security_group }}"
      instance_type: "{{ instance_size }}"
      instance_tags: "{{ instance_tags }}"
      image: "{{ ami_id }}"
      wait: yes
      vpc_subnet_id: "{{ subnet_id }}"
      assign_public_ip: no
