---
- name: apply specific Red Hat Security Advisory updates
  hosts: all

  tasks:
    - name: patch specific RHSA from a list
      command: yum -y update --advisory={{ item }}
      loop: "{{rhsa_patch_list}}"
      when: ansible_distribution_version == "8.4"
      notify: reboot_server

  handlers:
    - name: reboot_server
      reboot: